# Generated by Django 4.1.1 on 2022-11-10 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('sub_categoria', models.CharField(max_length=200)),
                ('rango', models.CharField(choices=[('1', 'De 0 a 15'), ('2', 'De 16 a 45'), ('3', 'De 46 en adelante')], max_length=1, verbose_name='Rango')),
                ('cantidad', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=200)),
                ('peso', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequenciaCardiaca', models.CharField(max_length=65, verbose_name='Frequencia Cardiaca(Heart Rate)')),
                ('saturacionOxigeno', models.CharField(max_length=65, verbose_name='Saturacion De Oxigeno en Sangre')),
                ('nivelEstres', models.CharField(choices=[('a', 'Alto'), ('b', 'Bajo'), ('n', 'Normal')], max_length=1, verbose_name='Nivel De Estres')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.persona')),
            ],
        ),
    ]
